# Site settings

# {{ site.title }}
title: Adobe InDesign Scripting 

# {{ site.email }}
email: ids@meen.ch

# {{ site.description }}
description: > 
  Adobe InDesign Scripting, Gemeinschaftsprojekt «Grafisches Forum Zürich» 
  und Berufsschule für Gestaltung Zürich medienformfarbe, entwickelt durch
  Andreas Eberhard, Jona.
baseurl: "/"
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  meengit

# Build settings
markdown: kramdown
# highlighter: rouge

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
# theme: minima
# gems:
#   - jekyll-feed
# 
# exclude:
#   - Gemfile
#   - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed
